dist: trusty
sudo: required
language: node_js

addons:
  sonarcloud:
    organization: "paulostation-github"
jdk:
  - oraclejdk8
cache:
  directories:
    # enable cache to speed up NodeJS builds
    - node_modules
    - '$HOME/.sonar/cache'

install:
  - npm install

script:
  - sonar-scanner 
    -Dsonar.projectKey=metadata-extractor
    -Dsonar.sources=. 
    -Dsonar.host.url=https://sonarcloud.io 
  - npm test || true

before_deploy:
 - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
 - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
 - sudo apt-get update
 - sudo apt-get install cf-cli

deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      branch: 
        - master
        - test
      type: push